version: '2'

services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    ports:
      - 30080:80
    working_dir: /app/
    volumes:
      - ./composer.json:/app/composer.json
      - ./config:/app/config
      - ./src:/app/src
      - ./public:/app/web
      - ./vendor:/app/vendor
      - ~/.composer-docker/cache:/root/.composer/cache:delegated